plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4

Style/Documentation:
  Enabled: false

# String literal is the default for ruby 3.4
Style/FrozenStringLiteralComment:
  Enabled: false

Style/WordArray:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
